//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electronics.Models
{
    using System;
    
    public partial class ArticleSubjectPair
    {
        public int ArticleID { get; set; }
        public int SubjectID { get; set; }
    }
}
